# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'

env:
  COVERAGE_OUT_FILE: coverage.out
  COVERAGE_HTML_FILE: coverage.html

tasks:
  lint:
    desc: Use golangci-lint (.golangci.yml).
    cmds:
      - golangci-lint run --fix
  test:
    desc: Run test.
    cmds:
      - go test ./...
  coverage:
    desc: Makes report coverage.
    cmds:
      - echo files $COVERAGE_OUT_FILE, $COVERAGE_HTML_FILE // -coverpkg=./... all files
      - go test -v ./... -covermode=count -coverprofile=$COVERAGE_OUT_FILE
      - go tool cover -html $COVERAGE_OUT_FILE -o $COVERAGE_HTML_FILE
      - go tool cover -func=$COVERAGE_OUT_FILE -o=$COVERAGE_OUT_FILE
  clean:
    desc: Clean binaries and reports.
    cmds:
      - rm -rf $BUILD_FOLDER
      - rm -rf $COVERAGE_OUT_FILE $COVERAGE_HTML_FILE
  download:
    desc: Run go mod tidy.
    cmds:
      - go mod tidy
  upgrade:
    desc: Check for latest direct dependencies.
    cmds:
      - go-mod-upgrade
  build:
    desc: Build the go EXECUTABLE.
    generates:
      - server
    interactive: true
    cmds:
      - go build ./...
  all:
    desc: Run relevant tasks.
    cmds:
      - task: clean
      - task: download
      - task: lint
      - task: test
      - task: coverage
      - task: build
  default:
    desc: Run [build] task.
    cmds:
      - task: build